package tools

import (
	"context"
	"encoding/json"
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

// Numeric shape: the entire string must be a valid JSON number; integer
// additionally forbids fractional and exponent parts. These two regexes must
// be identical across all four languages — without them, each language's
// string-to-number conversion has its own leniency (Go's ParseFloat accepts
// "inf", Python's int() accepts "1_000"), causing the same arguments to
// produce different values in different languages.
var (
	intShape = regexp.MustCompile(`^[+-]?\d+$`)
	numShape = regexp.MustCompile(`^[+-]?(\d+\.?\d*|\.\d+)([eE][+-]?\d+)?$`)
)

// MCPToolPrefix is the common prefix for all MCP tool names.
const MCPToolPrefix = "mcp__"

// MCPNameSep separates the server segment from the tool segment in MCP tool
// names. A double underscore makes the boundary reversible — server and tool
// names themselves may contain single underscores.
const MCPNameSep = "__"

// McpCallToolName is the dispatch tool's name, also used in permission rules.
const McpCallToolName = "McpCall"

// coerceScalar performs conservative type coercion based on the schema-declared
// type; returns the value unchanged if coercion is not possible.
func coerceScalar(value any, want string) any {
	switch want {
	case "string":
		// bool must not be coerced to "true" via the numeric path
		switch v := value.(type) {
		case float64:
			if v == float64(int64(v)) {
				return strconv.FormatInt(int64(v), 10)
			}
			return strconv.FormatFloat(v, 'f', -1, 64)
		case int:
			return strconv.Itoa(v)
		case int64:
			return strconv.FormatInt(v, 10)
		case json.Number:
			return v.String()
		}
	case "integer":
		if s, ok := value.(string); ok {
			text := strings.TrimSpace(s)
			// "5.7" against integer is not truncated; pass through for the MCP server to report its own domain error
			if !intShape.MatchString(text) {
				return value
			}
			if n, err := strconv.ParseInt(text, 10, 64); err == nil {
				return n
			}
		}
	case "number":
		if s, ok := value.(string); ok {
			text := strings.TrimSpace(s)
			if !numShape.MatchString(text) {
				return value
			}
			if f, err := strconv.ParseFloat(text, 64); err == nil {
				return f
			}
		}
	case "boolean":
		if s, ok := value.(string); ok {
			switch strings.ToLower(strings.TrimSpace(s)) {
			case "true":
				return true
			case "false":
				return false
			}
		}
	}
	return value
}

// CoerceBySchema recursively corrects model-supplied arguments against a JSON schema.
//
// When MCP tools are not in tools[], arguments are freely generated by the model
// without interface-level schema constraints, occasionally producing wrong JSON
// types. The correction rules below must be identical across all four languages:
//
//	schema declares     model supplies           corrected to
//	string              number                   "8891"
//	integer / number    numeric string           5 / 5.0
//	boolean             "true" / "false"         true / false
//	array               single-key object (array value)  unwrap inner array
//	array               comma-separated string   split on comma, trim whitespace
//	object              object                   recurse per properties
//	array               array                    recurse per items on each element
//
// Values that cannot be corrected pass through unchanged; the MCP server reports
// its own domain error, which is more instructive to the model than a local
// type error.
func CoerceBySchema(value any, schema any) any {
	schemaMap, ok := schema.(map[string]any)
	if !ok {
		return value
	}
	want, _ := schemaMap["type"].(string)

	if want == "object" {
		obj, ok := value.(map[string]any)
		if !ok {
			return value
		}
		props, _ := schemaMap["properties"].(map[string]any)
		out := make(map[string]any, len(obj))
		for k, v := range obj {
			if sub, found := props[k]; found {
				out[k] = CoerceBySchema(v, sub)
			} else {
				out[k] = v
			}
		}
		return out
	}

	if want == "array" {
		itemSchema := schemaMap["items"]
		// Models often wrap arrays as single-key objects like {"item": [...]}
		if obj, isObj := value.(map[string]any); isObj && len(obj) == 1 {
			for _, inner := range obj {
				if arr, isArr := inner.([]any); isArr {
					value = arr
				}
			}
		} else if s, isStr := value.(string); isStr {
			// Also commonly given as a comma-separated string
			parts := strings.Split(s, ",")
			arr := make([]any, 0, len(parts))
			for _, p := range parts {
				if t := strings.TrimSpace(p); t != "" {
					arr = append(arr, t)
				}
			}
			value = arr
		}
		if arr, isArr := value.([]any); isArr {
			out := make([]any, len(arr))
			for i, item := range arr {
				out[i] = CoerceBySchema(item, itemSchema)
			}
			return out
		}
		return value
	}

	if want != "" {
		return coerceScalar(value, want)
	}
	return value
}

// McpCallPermissionContent produces the permission-rule content, normalized to
// server__tool.
//
// It carries no mcp__ prefix and is unaffected by per-language wrapper naming
// differences, so permissions.yaml syntax is identical across all four
// languages: McpCall(linear__create_issue).
//
// Both segments are sanitized. The model may pass a short name or a full name;
// full-name segments are already processed by the wrapper, while short names
// come raw from the model — without uniform handling, the same call with a
// short name vs. a full name would produce different content and rules would
// fail to match.
func McpCallPermissionContent(server, tool string) string {
	if strings.HasPrefix(tool, MCPToolPrefix) {
		rest := strings.TrimPrefix(tool, MCPToolPrefix)
		// Full name already contains the server segment; use it to avoid producing linear__linear__x
		if idx := strings.Index(rest, MCPNameSep); idx >= 0 {
			return sanitizeSegment(rest[:idx]) + MCPNameSep +
				sanitizeSegment(rest[idx+len(MCPNameSep):])
		}
	}
	return sanitizeSegment(server) + MCPNameSep + sanitizeSegment(tool)
}

// McpCallTool is the unified invocation entry point for MCP tools.
//
// MCP tools do not enter tools[]; the model first reads the schema via
// ToolSearch, then passes the tool name and arguments here. This keeps the
// tools array byte-identical for the entire session so the prompt cache prefix
// is never invalidated — tools are rendered after system and before messages,
// so any array change forces the entire trailing history to be recomputed.
type McpCallTool struct {
	Registry *Registry
}

func (t *McpCallTool) Name() string { return McpCallToolName }

func (t *McpCallTool) Description() string {
	return "Invoke a tool on a connected MCP server. Call ToolSearch first to load " +
		"the tool's schema, then pass its arguments here exactly as that schema " +
		"requires, using the same JSON types."
}

func (t *McpCallTool) Category() ToolCategory { return CategoryCommand }

func (t *McpCallTool) Schema() map[string]any {
	return map[string]any{
		"name":        t.Name(),
		"description": t.Description(),
		"input_schema": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"server": map[string]any{
					"type":        "string",
					"description": "MCP server name, e.g. 'linear'.",
				},
				"tool": map[string]any{
					"type": "string",
					"description": "Full tool name as returned by ToolSearch, " +
						"e.g. 'mcp__linear__create_issue'.",
				},
				"arguments": map[string]any{
					"type": "object",
					"description": "The target tool's arguments. Must match that " +
						"tool's input_schema exactly, including JSON types: bare " +
						"numbers for integer fields, bare true/false for boolean " +
						"fields, quoted strings for string fields, and plain JSON " +
						"arrays for array fields.",
				},
			},
			"required": []string{"server", "tool", "arguments"},
		},
	}
}

// resolve tries full name, then server+short name, then unique suffix match.
//
// Models frequently pass only the short name (~30% of calls in practice);
// this must be tolerated, otherwise it costs a needless retry round.
func (t *McpCallTool) resolve(server, tool string) Tool {
	if found := t.Registry.Get(tool); found != nil {
		return found
	}
	if found := t.Registry.Get(MCPToolPrefix + sanitizeSegment(server) + MCPNameSep + sanitizeSegment(tool)); found != nil {
		return found
	}
	suffix := MCPNameSep + sanitizeSegment(tool)
	var matches []Tool
	for _, candidate := range t.Registry.ListTools() {
		name := candidate.Name()
		if strings.HasPrefix(name, MCPToolPrefix) && strings.HasSuffix(name, suffix) {
			matches = append(matches, candidate)
		}
	}
	if len(matches) == 1 {
		return matches[0]
	}
	return nil
}

// sanitizeSegment follows the same replacement rules as mcp.SanitizeName.
// It does not import internal/mcp to avoid a circular dependency.
func sanitizeSegment(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '_':
			b.WriteRune(r)
		default:
			b.WriteRune('_')
		}
	}
	return b.String()
}

func (t *McpCallTool) availableNames() []string {
	var names []string
	for _, candidate := range t.Registry.ListTools() {
		if strings.HasPrefix(candidate.Name(), MCPToolPrefix) {
			names = append(names, candidate.Name())
		}
	}
	sort.Strings(names)
	return names
}

func (t *McpCallTool) Execute(ctx context.Context, args map[string]any) ToolResult {
	server, _ := args["server"].(string)
	tool, _ := args["tool"].(string)
	if tool == "" {
		return ToolResult{Output: "McpCall requires a 'tool' name", IsError: true}
	}

	target := t.resolve(server, tool)
	if target == nil {
		names := t.availableNames()
		hint := "(none connected)"
		if len(names) > 0 {
			hint = strings.Join(names, ", ")
		}
		return ToolResult{
			Output: fmt.Sprintf(
				"Unknown MCP tool '%s' on server '%s'. Available tools: %s",
				tool, server, hint),
			IsError: true,
		}
	}

	inner, _ := args["arguments"].(map[string]any)
	if inner == nil {
		inner = map[string]any{}
	}
	if mt, ok := target.(MCPTool); ok {
		if schema := mt.MCPInputSchema(); len(schema) > 0 {
			if fixed, ok := CoerceBySchema(inner, schema).(map[string]any); ok {
				inner = fixed
			}
		}
	}
	return target.Execute(ctx, inner)
}
